### ISSUE TITLE
Should indicate from `init` whether or not we succeeded

### ISSUE THREAD

**Issue by torkelrogstad** [nchashch/drivechain-c#1]
The call to `init` should return a bool (or perhaps a more descriptive error message) that indicates if the Drivechain connection failed.

Context: I'm currently trying to setup the Ethereum sidechain, and I get a horrible panic deep within Rust and C bindings upon the first interaction with the mainchain because we're unable to connect properly. This should instead be reported earlier, when initialization fails.

**Comment by nchashch** [comment]
Fixed in [0c22cfc22debd0529db9d7b1d2ff2e137e17ca7a](https://github.com/nchashch/drivechain-c/commit/0c22cfc22debd0529db9d7b1d2ff2e137e17ca7a).
